services:
  postgres:
    image: postgres
    ports:
      - '5431:5432'
    environment:
      POSTGRES_DB: media_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
# psql -h localhost -p 5431 -d media_agent -U postgres